# permissions for end users to edit ides.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ide-editor-role
rules:
- apiGroups:
  - uengine.org
  resources:
  - ides
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uengine.org
  resources:
  - ides/status
  verbs:
  - get
