apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: ide-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: ide-operator by uEngine
  displayName: ide-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - uengine
  - msaez
  - ide
  links:
  - name: Ide Operator
    url: https://ide-operator.domain
  maintainers:
  - email: sanghoon01@uengine.org
    name: kim
  maturity: alpha
  provider:
    name: kim
    url: https://uengine.org
  version: 0.0.0
