kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.hashName }}
  namespace: {{ .Values.hashName }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
