apiVersion: v1
kind: Service
metadata:
  labels:
    environment: labs
    app: {{ .Values.hashName }}
    userId: email
  name: {{ .Values.hashName }}
  namespace: default
spec:
  ports:
  - name: port-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: port-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: port-8082
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: port-8083
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: port-8084
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: port-8085
    port: 8085
    protocol: TCP
    targetPort: 8085
  - name: port-8086
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: port-8087
    port: 8087
    protocol: TCP
    targetPort: 8087
  - name: port-8088
    port: 8088
    protocol: TCP
    targetPort: 8088
  - name: port-8089
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: {{ .Values.hashName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
