apiVersion: v
description: Build Education Server 
name: gcp-msaez
version: "1"
appVersion: master
keywords:
- Education
- Labs
home: https://uEngine.org
sources:
- https://source.cloud.google.com/eventstorming-tool
maintainers:
- name: Kim Sanghoon
  email: sanghoon01@uengine.org
