apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: ide-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ide-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: ide-operator-system
- kind: ServiceAccount
  name: ide-operator-system
  namespace: default
