apiVersion: v1
kind: Service
metadata:
  name: ide-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1338
  selector:
    app: ide-proxy
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: file-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: file-server
  sessionAffinity: None
