apiVersion: v1
kind: Service
metadata:
  name: {{ include "on-prem-helm.fullname" . }}
  labels:
    {{- include "on-prem-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "on-prem-helm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: api-server
---
apiVersion: v1
kind: Service
metadata:
  name: file-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: file-server
---
apiVersion: v1
kind: Service
metadata:
  name: ide-proxy
spec:
  type: ClusterIP
  ports:
    - port: 1338
      targetPort: 1338
      protocol: TCP
      name: http
  selector:
    app: ide-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: acebase
spec:
  type: ClusterIP
  ports:
    - port: 5757
      targetPort: 5757
      protocol: TCP
      name: http
  selector:
    app: acebase